# Generated by Django 3.1.4 on 2021-10-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211009_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbnails',
            new_name='thumb_down_count',
        ),
        migrations.AddField(
            model_name='post',
            name='thumb_up_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
